reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
script:
- xctool test -workspace Example/MightyIO-iOS-Pod.xcworkspace -scheme MightyIO-iOS-Pod -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
